global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.InteropServices;
global using System.Diagnostics;
global using DanilovSoft.Jpegli.Native.PInvoke;
global using DanilovSoft.Jpegli.Native.Exceptions;
global using uint8_t = System.Byte;
global using uint16_t = System.UInt16;
global using uint32_t = System.UInt32;
global using uint64_t = System.UInt64;
global using int8_t = System.SByte;
global using int16_t = System.Int16;
global using int32_t = System.Int32;
global using int64_t = System.Int64;
global using size_t = System.Int64;
